version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        patterns:
          - "*"
        dependency-type: development
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    target-branch: staging
    schedule:
      interval: weekly
