import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';

export interface CodegraphStats {
  indexed: boolean;
  index_path?: string;
  index_age_days?: number;
  symbol_count?: number;
  file_count?: number;
  error?: string;
}

const DEFAULT_EXCLUDES = [
  'node_modules',
  'build',
  '.gradle',
  'dist',
  'target',
  '.git',
  '.agentic-setup',
  '.codegraph',
];

export const CODEGRAPH_MCP_SERVER = {
  command: 'npx',
  args: ['-y', 'codegraph-ai', 'serve', '--watch', '${workspaceFolder}'],
};

export function getExcludePatterns(): string[] {
  return DEFAULT_EXCLUDES;
}

export function runCodegraphIndex(
  repoRoot: string,
  options: { timeoutMs?: number } = {},
): { ok: boolean; output: string } {
  const args = ['-y', 'codegraph-ai', 'index', repoRoot];
  for (const ex of getExcludePatterns()) {
    args.push('--exclude', ex);
  }
  try {
    const output = execFileSync('npx', args, {
      cwd: repoRoot,
      encoding: 'utf-8',
      timeout: options.timeoutMs ?? 600_000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return { ok: true, output };
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string };
    return {
      ok: false,
      output: (e.stdout || '') + (e.stderr || ''),
    };
  }
}

export function getCodegraphStats(repoRoot: string): CodegraphStats {
  const candidates = [path.join(repoRoot, '.codegraph'), path.join(repoRoot, 'codegraph.db')];

  for (const indexPath of candidates) {
    if (fs.existsSync(indexPath)) {
      let ageDays: number | undefined;
      try {
        const mtime = fs.statSync(indexPath).mtimeMs;
        ageDays = Math.floor((Date.now() - mtime) / (1000 * 60 * 60 * 24));
      } catch {
        // ignore
      }
      return { indexed: true, index_path: indexPath, index_age_days: ageDays };
    }
  }
  return { indexed: false };
}

function readCliVersion(command: string, args: string[]): string | null {
  try {
    return execFileSync(command, args, {
      encoding: 'utf-8',
      timeout: 3_000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return null;
  }
}

/** Fast availability probe — never uses `npx -y` (downloads on cold CI/cache). */
export function checkCodegraphCli(repoRoot = process.cwd()): {
  available: boolean;
  version?: string;
} {
  const localBin = path.join(repoRoot, 'node_modules', '.bin', 'codegraph-ai');
  if (fs.existsSync(localBin)) {
    const version = readCliVersion(localBin, ['--version']);
    if (version) return { available: true, version };
  }

  const version = readCliVersion('npx', ['--no-install', 'codegraph-ai', '--version']);
  if (version) return { available: true, version };

  return { available: false };
}

export function mergeCodegraphMcp(repoRoot: string, dryRun = false): boolean {
  const mcpPath = path.join(repoRoot, '.cursor', 'mcp.json');
  if (!fs.existsSync(path.dirname(mcpPath))) {
    fs.mkdirSync(path.dirname(mcpPath), { recursive: true });
  }

  let existing: { mcpServers?: Record<string, unknown> } = { mcpServers: {} };
  if (fs.existsSync(mcpPath)) {
    try {
      existing = JSON.parse(fs.readFileSync(mcpPath, 'utf-8'));
    } catch {
      existing = { mcpServers: {} };
    }
  }

  if (!existing.mcpServers) existing.mcpServers = {};
  if (existing.mcpServers.codegraph) return false;

  existing.mcpServers.codegraph = CODEGRAPH_MCP_SERVER;
  if (!dryRun) {
    fs.writeFileSync(mcpPath, JSON.stringify(existing, null, 2));
  }
  return true;
}

export function writeIndexScript(repoRoot: string, dryRun = false): string {
  const scriptPath = path.join(repoRoot, 'scripts', 'index-codegraph.sh');
  const excludes = getExcludePatterns()
    .map((e) => `  --exclude ${e}`)
    .join(' \\\n');

  const content = `#!/usr/bin/env bash
# Generated by agentic-setup — index this repo for Codegraph MCP
set -euo pipefail
cd "$(dirname "$0")/.."
npx -y codegraph-ai index . \\
${excludes}
echo "Codegraph index complete."
`;

  if (!dryRun) {
    fs.mkdirSync(path.dirname(scriptPath), { recursive: true });
    fs.writeFileSync(scriptPath, content, { mode: 0o755 });
  }
  return scriptPath;
}

export function appendGitignoreEntries(repoRoot: string, dryRun = false): void {
  const gitignorePath = path.join(repoRoot, '.gitignore');
  const marker = '# agentic-setup codegraph';
  const content = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, 'utf-8') : '';
  if (content.includes(marker)) return;

  const block = `\n${marker}\n.codegraph/\ncodegraph.db\n`;
  if (!dryRun) {
    fs.writeFileSync(gitignorePath, content + block);
  }
}

export function parseIndexOutput(output: string): Partial<CodegraphStats> {
  const stats: Partial<CodegraphStats> = {};
  const symbolMatch = output.match(/(\d+)\s+symbols?/i);
  const fileMatch = output.match(/(\d+)\s+files?/i);
  if (symbolMatch) stats.symbol_count = parseInt(symbolMatch[1], 10);
  if (fileMatch) stats.file_count = parseInt(fileMatch[1], 10);
  return stats;
}

export function readMcpConfig(repoRoot: string): { valid: boolean; hasCodegraph: boolean } {
  const mcpPath = path.join(repoRoot, '.cursor', 'mcp.json');
  if (!fs.existsSync(mcpPath)) return { valid: false, hasCodegraph: false };
  try {
    const config = JSON.parse(fs.readFileSync(mcpPath, 'utf-8')) as {
      mcpServers?: Record<string, unknown>;
    };
    return { valid: true, hasCodegraph: Boolean(config.mcpServers?.codegraph) };
  } catch {
    return { valid: false, hasCodegraph: false };
  }
}
